spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/test?allowMultiQueries=true&amp;characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: org.rqing.demo.mybatis.dao
  mapper-locations:
  - classpath:**/mapper/*.xml
mapper:
  mappers:
  - org.rqing.demo.mybatis.util.PageHelperMapper
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql